### ISSUE TITLE
XMPP Custom Server

### ISSUE THREAD

**Issue by jeremyrichardmann** [saqura/xmppwb#2]
Since Cisco's implementation of Jabber is terrible, finding the service via DNS is next to impossible at my org.  Any options for customizing the server that it's trying to connect with?

**Comment by saqura** [comment]
The current master now allows to specify a `host` and a `port` in the config like this:

``` yaml
xmpp:
  jid: <jid>
  host: <hostname>
  port: <port>
  password: <password>
...
```

Please let me know if it works with these settings. The changes are not in PyPi yet so to test it you have to use the git version. One way to test it would be like this, using virtualenv and bash:

```
mkdir xmppwb
cd xmppwb
virtualenv env
source env/bin/activate
pip install --upgrade git+https://github.com/saqura/xmppwb
xmppwb -h
```
