### ISSUE TITLE
MUCs needed in config, even if no MUCs in place

### ISSUE THREAD

**Issue by rasos** [saqura/xmppwb#8]
We had discovered a minor issue:
You can not omit the mucs section in bridge.conf
Here is our workaround:

```
 # A list of all MUCs that should be available to the bridges defined later.
  # none, as MUCs are not supported by IM+ client for Windows Phone, but we define one, seems needed
  mucs:
     - jid: nonexistent@conference.myxmppserver.at
       nickname: nonexistent
```
